language: python
python:
  - "3.4"
  - "2.7"
install: 
  - pip install ply
  - pip install coveralls
script:
  - coverage run --source=xtuml setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
